# Generated by Django 5.0.1 on 2025-03-03 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reniorsapp', '0005_facility_facilityimage_facilityvideo'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='quickservice_images/')),
            ],
        ),
    ]
