# Generated by Django 5.0.1 on 2025-03-03 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reniorsapp', '0006_quickservice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('details', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
