# Generated by Django 5.0.1 on 2025-03-03 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reniorsapp', '0007_package'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_name', models.CharField(max_length=255)),
                ('article_image', models.ImageField(blank=True, null=True, upload_to='articles/')),
                ('article_description', models.TextField()),
            ],
        ),
    ]
